name: NotifierScript
on:
  push:
  schedule:
    - cron: "*/5 * * * *"

env:
  URL: ${{vars.URL}}
  SIZE: ${{vars.SIZE}}
  TO: ${{secrets.TO}}
  FROM: ${{secrets.FROM}}
  ACCOUNT_SID: ${{secrets.ACCOUNT_SID}}
  AUTH_TOKEN: ${{secrets.AUTH_TOKEN}}

jobs:
  build:
    environment: PROD
    runs-on: ubuntu-latest
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v3
      - name: Show env variables
        run: |
          env
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Python Script
        run: |
          python main.py 


